pragma solidity ^0.4.0;
contract Digitaalisuusreflektiot {

/*
Digitaalisen yhteiskunnan rajapinnoilla
N&#228;m&#228; reflektiot kuuluvat osana Helsingin yliopistolla syksyll&#228; 2017 j&#228;rjestetyn ”Digitaalisen yhteiskunnan rajapinnoilla” -kurssin suorittamiseen. Kurssin aiheena oli teknologiav&#228;litteinen sosiaalinen toiminta eri digitaalisilla areenoilla. Tarkoitus on reflektoida opittua, k&#228;ytt&#228;&#228; kurssikirjallisuutta sek&#228; muuta materiaalia ja edist&#228;&#228; ymm&#228;rryst&#228; verkon luonteesta kulttuurisena ja sosiaalisena muotona. Reflektiot esitet&#228;&#228;n luentokohtaisesti kuudesta luennosta (luennot 1-6).


30.10. INTROLUENTO: MIT&#196; ON DIGITAALINEN YHTEISKUNTATIEDE?

Aluksi taustoituksena on hyv&#228; mainita, ett&#228; el&#228;mme erityisen suuren murroksen aikakautta. T&#228;t&#228; murrosta on kutsuttu toiseksi kommunikaatiovallankumoukseksi; noin sata vuotta sitten tapahtunut ensimm&#228;inen kommunikaatiovallankumous perustui hierarkiaan (organisaatiot, infrastruktuuri ja massamedia). Nyt tapahtuva toinen kommunikaatiovallankumous perustuu joustavaan verkostorakenteeseen (verkko korvaa perinteisi&#228; viestint&#228;- ja logistiikkav&#228;yli&#228;, segmentoitunut ja henkil&#246;kohtainen kommunikaatio) (van Dijk 2012). Murros on synnytt&#228;nyt uusia tieteenaloja, kuten esimerkiksi Internetin tutkimuksen (Internet studies), joka on nopeasti laajeneva monitieteinen tieteenala (Dutton 2014). Monitieteisyydest&#228; puhuttiin my&#246;s luennoilla; ne korostivat tarvetta humanististen painotusten vahvistamiseen.
”Kuluttajakansalaiset datataloudessa”-luennon aiheena oli kuluttajakansalaisen arki datataloudessa ja digitalisoitumiskehitys sek&#228; muutokset kuluttajan roolissa. Datakansalainen-sana her&#228;tt&#228;&#228; ajatuksen alamaisuudesta; toimimme suurten dataj&#228;ttien ehtojen mukaan ja meill&#228; on n&#228;enn&#228;inen kyky vaikuttaa esimerkiksi likett&#228;m&#228;ll&#228;, klikkaamalla tai googlaamalla, mutta meill&#228; ei varsinaisesti ole mahdollisuutta vaikuttaa algoritmeihin tai dataj&#228;ttien p&#228;&#228;t&#246;ksentekoon. T&#228;m&#228; asettaa datakansalainen-k&#228;sitteen kyseenalaiseksi. El&#228;mmek&#246; enemm&#228;nkin autoritaarisessa n&#228;enn&#228;isdatademokratiassa, jossa meille annetaan illuusio mahdollisuudesta vaikuttaa asioihin, vaikka todellisuudessa olemme j&#228;ttien alamaisia?
Teknologinen kehitys on muovannut kuluttajan roolia vastaanottajasta informaation prosessoijaksi, sis&#228;ll&#246;ntuottajaksi ja edelleen arvontuotannon l&#228;hteeksi. T&#228;m&#228;n kehityksen seurauksena meist&#228; on tullut &#228;lykk&#228;it&#228; sensoreita joista ker&#228;t&#228;&#228;n paljon dataa, josta korvaukseksi voimme k&#228;ytt&#228;&#228; yritysten tarjoamia palveluja. Hy&#246;dyt ovat todenn&#228;k&#246;isesti suurempia kuin haitat, koska pysymme kuitenkin n&#228;iden palveluiden k&#228;ytt&#228;jin&#228;. Emme v&#228;ltt&#228;m&#228;tt&#228; kuitenkaan tied&#228;, miten ja millaista dataa meist&#228; ker&#228;t&#228;&#228;n. Luennolla mainittiin muun muassa nukkevakooja, joka ker&#228;&#228; lasten el&#228;m&#228;st&#228; tietoa. Nuken ostaja ei v&#228;ltt&#228;m&#228;tt&#228; tule edes ajatelleeksi tai kiinnitt&#228;neeksi huomiota siihen, mit&#228; nukke tekee. Kaikki datankeruu ei kuitenkaan v&#228;ltt&#228;m&#228;tt&#228; ole huono asia; nukkevakooja voi esimerkiksi oppia reagoimaan lapsen eleisiin tai puheeseen, mill&#228; voi olla yhteys lapsen parempaan viihtyvyyteen ja mahdollisuuteen jatkokehitt&#228;&#228; tuotetta, jolloin datankeruusta on hy&#246;ty&#228; kaikille osapuolille. Rifkin on luennon mukaan esitt&#228;nyt ajatuksen yksityisyydensuojan menett&#228;misest&#228;. Hyv&#228; kysymys on, n&#228;emmek&#246; tai tied&#228;mmek&#246; kuinka paljon dataamme hy&#246;dynnet&#228;&#228;n yritysten toimesta. 
”Digitaalinen kulttuuri ja sosiaalisuus”-luento esitteli digitaalisen kulttuurin ja sosiaalisuuden tutkimuksellisia l&#228;ht&#246;kohtia. Aiheena olivat muun muassa kulttuurin muutokset ja disruptiot. Mielest&#228;ni luento n&#228;ki digitaalisen kulttuurin kriittisess&#228; valossa. Kauhukuvia ovat esimerkiksi sitoutuminen itsemittausteknologiaan koneen osaksi ja vanhusten ja lasten sys&#228;&#228;minen hoivarobottien hoidettavaksi. En kuitenkaan sanoisi, ett&#228; riippuvuus itsemittausteknologiasta olisi pelk&#228;st&#228;&#228;n huono asia. Itsemittausteknologia saattaa esimerkiksi pelastaa ihmisen burnoutilta tai ennaltaehk&#228;ist&#228; sairauden syntymist&#228;, koska itsemittausteknologia tunnistaa heikkoja signaaleja ihmisen kunnon ja terveyden heikkenemisest&#228; ennen kuin tilanne on mennyt liian pitk&#228;lle. 
Kulttuurin muutosta tarkastellaan my&#246;s kurssin oheiskirjallisuudessa; esimerkiksi van Dijk (2012) esitt&#228;&#228; The Network Society -kirjassa huolen sosiaalisen ymp&#228;rist&#246;n saastumisesta. Uuden kommunikaatioteknologian on ajateltu olevan haitallista sosiaaliselle vuorovaikutukselle, mutta vastakkaisen n&#228;kemyksen mukaan kommunikaatioteknologia laajentaa face-to-face-ulottuvuutta sen sijaan, ett&#228; se korvaisi sen. Baymin (2015) mukaan emme puhu dystopiasta en&#228;&#228; puhelinteknologian osalta: teknologiat ik&#228;&#228;n kuin normalisoituvat (domesticate, teknologia kesytet&#228;&#228;n). T&#228;m&#228; on prosessi, jossa villist&#228; teknologiasta kesytet&#228;&#228;n p&#228;ivitt&#228;inen asia. (Baym 2015.) Nykyiset kauhukuvat voivat t&#228;ss&#228; mieless&#228; olla luonnollinen osa siirtym&#228;vaihetta ennen teknologian omaksumista luonnolliseksi osaksi arkea. Yht&#228;&#228;lt&#228; uudet yhteydenpidon muodot on n&#228;hty uhkana yhteydenpidolle ja ihmistenv&#228;lisille suhteille, mutta toisaalta ne tarjoavat mahdollisuuksia muodostaa yhteyksi&#228; uusiin ihmisiin sek&#228; mahdollisuuksia vahvistaa ihmissuhteita.
Luennolla esitettiin kahteen kertaan ajatus muutoksesta deittailukulttuurissa; deittailusta on tullut nettideittailun my&#246;t&#228; entist&#228; intensiivisemp&#228;&#228; ja paikkaperusteisempaa. Perehdyin nettideittailun kulttuuria muokkaaviin vaikutuksiin tarkemmin kurssikirjallisuuden kautta. Duttonin (2014) kirja Handbook of Internet Studies tarkastelee nettideittailua kokonaisen artikkelin laajuudessa: “The Study of Online Relationships and Dating”. Artikkelin mukaan nettideittailussa ollaan selektiivisempi&#228; ja suunnitelmallisempia sen suhteen, mit&#228; itsest&#228; kerrotaan vastapuolelle. On my&#246;s huomattu, ett&#228; nettideittailijat voivat systemaattisesti v&#228;&#228;rist&#228;&#228; kuvaa itsest&#228;&#228;n parantaakseen mahdollisuuksiaan deittailumarkkinoilla. (Dutton 2014.) van Dijkin mukaan deittailu muuttuu liiketoiminnan kaltaiseksi tietyill&#228; ominaisuuksilla varustetun henkil&#246;n etsinn&#228;ksi. Tietyt ominaisuudet ja asenteet omaava henkil&#246; on helpompi l&#246;yt&#228;&#228; nettideittailun kautta. Suhde on helppo korvata toisella. Suhteet voivat lyhenty&#228;, ja traditionaaliset flirttailun tavat heikentyv&#228;t. (van Dijk 2012, s. 264.) Tinderi&#228; on mediassa haukuttu siit&#228;, ett&#228; se edist&#228;&#228; kertak&#228;ytt&#246;ist&#228; deittailukulttuuria (ks. Guardian 16.08.2015). Lis&#228;ksi Internetiss&#228; virtuaalisesti luodut ihmissuhteet eiv&#228;t v&#228;ltt&#228;m&#228;tt&#228; tunnu oikeilta ihmissuhteilta (Baym 2015). Uskoisin silti, ett&#228; vaikka nettideittailuun liittyy tiettyj&#228; ongelmakohtia, ilmi&#246; ei ole niin yksiselitteinen ja siihen liittyy sek&#228; haittoja ett&#228; hy&#246;tyj&#228;.
Esimerkkej&#228; kulttuurisesta muutoksesta voidaan l&#246;yt&#228;&#228; loputtomiin. Kirjaa lukiessani oivalsin, ett&#228; my&#246;s sellainen asia kuin esimerkiksi sodank&#228;ynti on muutoksessa. Sodank&#228;ynti on siirtym&#228;ss&#228; osittain verkkoon (ns. cyber-war); pyrkimyksen&#228; on aiheuttaa vahinkoa tai h&#228;iri&#246;t&#228; toisen maan verkossa. Varsinaista laajamittaista cyber-sotaa ei ole ainakaan viel&#228; ollut, mutta tiettyjen maiden hallitukset ovat olleet osallisina cyber-hy&#246;kk&#228;yksiss&#228;. (van Dijk 2012.) 

L&#228;hteet
Baym, Nancy (2015) Personal Relations in the Digital Age.
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Dutton, William (2014) Handbook of Internet Studies.
Guardian 16.08.2015: Is Tinder really creating a ‘dating apocalypse’? Viitattu  13.12.2017. Saatavissa: https://www.theguardian.com/technology/2015/aug/16/tinder-app-creating-dating-apocalypse-twitter-storm 

6.11. IDENTITEETTI, ADDIKTIO JA TEKNOLOGIA

Toisen luennon ensimm&#228;isen osuuden aiheena olivat addiktiot. K&#228;ytt&#228;j&#228;kokemus ei ole ainoa informaatioteknologian kehityst&#228; ohjaava tekij&#228;, vaan sen lis&#228;ksi ohjelmistot ja laitteet suunnitellaan siten, ett&#228; k&#228;ytt&#228;j&#228; addiktoituu niihin. “&#39;Our minds can be hijacked&#39;: the tech insiders who fear a smartphone dystopia”-artikkeli tarjoaa esimerkkej&#228; addiktoivasta designista; Facebookin “tykk&#228;&#228;”-toiminto tuottaa pseudomielihyv&#228;&#228;. Sosiaalisen median toimintalogiikkaa voidaan verrata uhkapelaamiseen: punaisten ikonien klikkaaminen on kuin osallistuisi arpajaisiin, alasp&#228;in pyyhk&#228;isyyn perustuva p&#228;ivitystoiminto on kuin hedelm&#228;peli. (Quardian 6.10.2017.) N&#228;it&#228; ominaisuuksia ei v&#228;ltt&#228;m&#228;tt&#228; tule ajatelleeksi, koska k&#228;ytt&#228;j&#228; ei v&#228;ltt&#228;m&#228;tt&#228; tiedosta ohjelmistokehityksen motiiveja. Tietoisuus ongelmista on kuitenkin noussut yhteiskunnalliseen keskusteluun mediassa, esimerkiksi Helsingin sanomat ja YLE ovat viime viikkoina kirjoittaneet sosiaalisen median haitallisuudesta.
Sosiaalisen median psykologisista seurauksista k&#228;ytt&#228;jille ja yhteiskunnalle ollaan oltu huolissaan; yksil&#246;tasolla voi seurauksena olla keskittymiskyvyn heikkeneminen, yhteiskunnan kannalta seurauksena on niin sanottu huomiotalous oireineen (Quardian 6.10.2017). Huomiotaloudessa kohut saavat julkisuutta. Kun ajatellaan ett&#228; perinteisesti median rooli on ollut sivist&#228;&#228; kansalaisia, kohujen ja mielihyv&#228;keskeisyyden vaikutus yleiselle moraalille voi olla p&#228;invastainen. Addiktioista puhuttiin luennolla l&#228;hinn&#228; negatiivisessa valossa. Mielihyv&#228;n tavoittelu ja addiktiot voivat joissain tilanteissa olla eteenp&#228;in ajava voima, jos ne kohdistuvat olennaisiin asioihin, jotka viev&#228;t yksil&#246;&#228; el&#228;m&#228;ss&#228; eteenp&#228;in; esimerkiksi yksil&#246; voi olla addiktoitunut opiskeluun tai ty&#246;h&#246;n. Ongelma voikin olla se. ett&#228; ihmiset keskittyv&#228;t v&#228;&#228;riin asioihin, kuten esimerkiksi kissavideoihin. Ei tosin ole aiheellista v&#228;itt&#228;&#228;, ett&#228; kissavideot olisivat pelk&#228;st&#228;&#228;n huono asia. 
Luennon sokerihiiriesimerkiss&#228; ja Quardianin artikkelissa v&#228;itettiin, ett&#228; addiktioiden vuoksi tarvitaan keinotekoisia s&#228;&#228;nt&#246;j&#228;. Olen asiasta eri mielt&#228;. Merkityksellisen tekemisen etsiminen voi mahdollisesti auttaa; kun yksil&#246;ll&#228; on merkityksellist&#228; tekemist&#228;, aikaa addiktioille ei ole. Lis&#228;ksi olen eri mielt&#228; siit&#228; ett&#228; el&#228;m&#228;n pit&#228;isi jatkuvasti olla el&#228;myksellist&#228; tai yll&#228;tyksellist&#228;. Luennolla mainittiin teoria, jonka mukaan nautinto on opittu ominaisuus; mielest&#228;ni el&#228;myshakuisuus ja tarve yll&#228;tyksellisyyteen ovat vastaavasti opittuja ominaisuuksia. Mediassa on puhuttu digi&#228;hkyst&#228; ja halusta luopua &#228;lypuhelimesta (ks. YLE 20.06.2017); addiktoitumisen ongelma n&#228;ytt&#228;isi olevan todellinen, vaikka sit&#228; t&#228;ss&#228; v&#228;h&#228;ttelen.
“Identiteetti ja teknologia”-luennolla tarkasteltiin identiteetti&#228; sosiaalisen median aikakaudella. Voin samaistua sosiaalisen median aiheuttamaan identiteettikonfliktiin; sosiaaliseen mediaan on vaikea kirjoittaa, koska viestin tulee olla sopiva kaikille kavereille. Uskin ja Lampisen (2016) artikkeli sosiaalisista normeista ja itseilmaisusta sosiaalisen median sivuilla tarjoaa n&#228;kemyksi&#228; siit&#228;, miten joudumme tekem&#228;&#228;n profiility&#246;t&#228; ja sopeutumaan sosiaalisiin normeihin. Artikkelin l&#246;yd&#246;s oli se, ett&#228; sosiaalisessa mediassa pyrit&#228;&#228;n autenttisuuteen. Baym (2015) esitt&#228;&#228; kirjassaan vastakkaisen n&#228;kemyksen, jonka mukaan internetiss&#228; voi teeskennell&#228; ja valehdella, koska digitaalinen media erottaa minuuden kehosta. Internet tarjoaa yksil&#246;lle mahdollisuuksia  kokeilla erilaisia identiteettej&#228; ja olla erilainen yksil&#246; eri alustoilla; esimerkiksi musiikkifani lasf.fm:ss&#228; ja akateeminen henkil&#246; LinkedIn:ss&#228;. Huijaamisen mahdollisuudesta huolimatta kirjan mukaan ihmiset ovat rehellisempi&#228; netiss&#228; kuin kasvotusten. Yht&#228;&#228;lt&#228; internet mahdollistaa valehtelemisen ja teeskentelyn, mutta toisaalta internetiss&#228; on mahdollista esitt&#228;&#228; vapaammin todellista minuuttaan ja t&#228;ss&#228; mieless&#228; internet voi olla vapauttava. (Baym 2015.)
Luennolla spekuloitiin lasten ja nuorten alkoholin k&#228;yt&#246;n v&#228;hentymisen syit&#228;: johtuisiko siit&#228; ett&#228; pelk&#228;&#228; joutuvansa someen, vai houkuttaako terveystrendi? Itselleni tuli mieleen kolmas mahdollinen selitys; nuorten aika menee internetiss&#228; ja sosiaalisessa mediassa, addiktiot kohdistuvat peleihin ja tietokoneella olemiseen, jolloin alkoholi menett&#228;&#228; merkityst&#228;&#228;n addiktion kohteena ja ajanvieton muotona.
Snapchat toimii hyv&#228;n&#228; case-esimerkkin&#228; addiktoivasta ohjelmistokehityksest&#228;. Suomen kuvalehti (01.12.2017) esittelee Snapchatin toteutusta; Snapchat on sosiaalinen media, jonka Streak-luku osoittaa kuinka monta p&#228;iv&#228;&#228; kaverukset ovat yht&#228;jaksoisesti viestitelleet toisilleen. Luku nollaantuu jos viestittelyyn tulee yli vuorokauden tauko, tiimalasi varoittaa nollaantumisesta k&#228;ytt&#228;j&#228;lle; t&#228;ll&#228; designilla Snapchat pyrkii koukuttamaan k&#228;ytt&#228;j&#228;n jatkamaan yhteydenpitoa kaveriensa kanssa. Yhteydenpito on ik&#228;&#228;n kuin sosiaalinen peli, jossa suosion mittarina on Snapchatin Streak-luku. Luku voi aiheuttaa riippuvuutta, mutta toisaalta se edist&#228;&#228; sosiaalisten suhteiden muodostumista, verkostoitumista ja itsevarmuutta. (Suomen kuvalehti 01.12.2017.) Sosiaalisen median hyvyys tai huonous riippuu n&#228;in ollen n&#228;k&#246;kulmasta. Amerikassa tehdyn tutkimuksen mukaan internetin k&#228;ytt&#228;j&#228;t pit&#228;v&#228;t enemm&#228;n yhteytt&#228; l&#228;himm&#228;isiins&#228;, kavereihin ja kollegoihin verrattuna niihin jotka eiv&#228;t k&#228;yt&#228; internetti&#228; (Baym 2015, s. 141). 

L&#228;hteet
Baym, Nancy (2015) Personal Relations in the Digital Age.
Quardian 6.10.2017: &#39;Our minds can be hijacked&#39;: the tech insiders who fear a smartphone dystopia. Viitattu  13.12.2017. Saatavissa: https://www.theguardian.com/technology/2017/oct/05/smartphone-addiction-silicon-valley-dystopia
Suomen kuvalehti 01.12.2017: Snapchat kannustaa teinej&#228; pit&#228;m&#228;&#228;n ystavyyssuhteita yll&#228; kellon ymp&#228;ri. Viitattu  13.12.2017. Saatavissa: https://suomenkuvalehti.fi/jutut/kotimaa/snapchat-kannustaa-teineja-pitamaan-ystavyyssuhteita-ylla-kellon-ympari/?shared=996419-98c31999-999
Uski, S., &amp; Lampinen, A. (2016). Social norms and self-presentation on social network sites: Profile work in action. New media &amp; society, 18(3), 447-464.
YLE 20.06.2017: &quot;Hylk&#228;sin Facebookin, luovuin &#228;lypuhelimesta, vaihdoin vanhaan” – kolme tarinaa siit&#228;, miten digi&#228;hkyn voi sel&#228;tt&#228;&#228;. Viitattu  13.12.2017. Saatavissa: https://yle.fi/aihe/artikkeli/2017/06/20/hylkasin-facebookin-luovuin-alypuhelimesta-vaihdoin-vanhaan-kolme-tarinaa-siita

13.11. N&#196;K&#214;KULMIA POLITIIKKAAN JA TEKNOLOGIAAN

”Demokratian tukeminen teknologialla”-luennolla teknologian vaikutuksesta politiikkaan oltiin pessimistisi&#228;; luennolla mainittiin muun muassa valeuutiset ja verkkosivujen (esim. Kansalaisaloite.fi) toimimattomuus. Lis&#228;ksi demokratian kannalta olennainen kysymys on, onko internet vapauden vai kontrollin teknologia? van Dijk (2012) k&#228;sittelee aihetta kirjassaan. H&#228;nen mukaansa internet voi toimia demokraattisena ty&#246;kaluna ja v&#228;hent&#228;&#228; riippuvuutta massamediasta. K&#228;ytt&#228;jist&#228; tulee sis&#228;ll&#246;ntuottajia ja osallistujia. Politiikasta tulee entist&#228; enemm&#228;n verkottunutta; internet korvaa televisiota ja lehdist&#246;&#228; poliittisen keskustelun areenana. Internet ei kuitenkaan ole demokraattinen, koska sek&#228; autoritaariset ett&#228; demokraattiset valtiot pyrkiv&#228;t kontrolloimaan sit&#228;. (van Dijk 2012.) Demokratian tukeminen kontrollin teknologialla sis&#228;lt&#228;&#228; vivahteita autorit&#228;&#228;risyydest&#228;, jossa dataj&#228;tit ja maiden hallitukset hallitsevat ja manipuloivat kansalaisten ajatuksia ja mielipiteit&#228;. Vapauden teknologiana internet on my&#246;s ongelmallinen, sill&#228; vapaa ja s&#228;&#228;ntelem&#228;t&#246;n ymp&#228;rist&#246; on dataj&#228;ttien etu. 
Etsin internetist&#228; lis&#228;tietoa siit&#228;, millaisia valeuutisia maailmalla on liikkunut ja mit&#228; seurauksia niill&#228; on ollut. Yhten&#228; esimerkkin&#228; voidaan mainita Intiassa levinneet valheelliset WhatsApp-viestit, joiden mukaan miesjoukko kaappasi lapsia; viestit johtivat seitsem&#228;n ihmisen kuolemaan (BBC 24.07.2017). T&#228;m&#228; esimerkki osoittaa sen, ett&#228; vapaasta tiedonv&#228;lityksest&#228; ei aina seuraa pelkk&#228;&#228; hyv&#228;&#228;.
Kurssilukemiston “Do Artifacts Have Politics?”-artikkelissa esitettiin kaksi tapaa, joilla artefaktit voivat toimia poliittisesti (Winner 1980). Artefaktit tuottavat joillekin osapuolille poliittisia hy&#246;tyj&#228;, toisille haittoja. Siltojen osalta on helppo huomata, ett&#228; ne rajoittavat bussien mahdollisuuksia liikkua. Siltoja suunnitellessa seuraukset ovat usein my&#246;s odotettavissa. Algoritmien poliittiset seuraukset tuntuvat siltoihin verrattuna hankalalta hahmottaa. Niiden osalta emme tied&#228;, miten ne on suunniteltu ja kun algoritmissa on eritt&#228;in suuri m&#228;&#228;r&#228; muuttujia, edes niiden suunnittelija ei voi varmuudella tiet&#228;&#228; mit&#228; seurauksia niill&#228; on. Algoritmeja suunniteltaessa odottamattomien seurausten mahdollisuus voi n&#228;in ollen olla suuri. Joissain tilanteissa, esimerkiksi kun viestin pituus on rajoitettu 160 merkkiin, seuraukset ovat selke&#228;mmin n&#228;ht&#228;viss&#228;.
Luennolla mainittiin k&#228;sitteet teknologinen determinismi ja teknologinen sosiaalinen konstruktionismi. Perehdyin n&#228;ihin k&#228;sitteisiin tarkemmin Baymin (2015) kirjan kautta. Teknologisen determinismin mukaan teknologia ja laitteet muuttavat meit&#228;. Huolenaiheena on ollut muun muassa internet-teknologian vaikutus &#228;lykkyyteen ja muistamiskykyyn. Teknologisen determinismin n&#228;k&#246;kulmassa esitet&#228;&#228;n, ett&#228; negatiiviset vaikutukset voidaan poistaa teknologiaan kehitt&#228;m&#228;ll&#228;. Teknologian sosiaalinen konstruktionismis mukaan ihmisill&#228; on valta; ihmiset ovat muutoksen agentteja, joiden toimista teknologiat syntyv&#228;t. (Baym 2015.) Aiemmilla luennoilla puhuimme l&#228;hinn&#228; teknologiasta luopumisesta tai sen k&#228;yt&#246;n v&#228;hent&#228;misest&#228;, joka on vastakkainen n&#228;kemys Baymin esitt&#228;m&#228;&#228;n ajatukseen ongelmien ratkaisemisesta teknologiaa kehitt&#228;m&#228;ll&#228;. Ongelmien ratkaiseminen teknologiaa kehitt&#228;m&#228;ll&#228; on n&#228;kemys joka liittyy teknologiseen determinismiin, joka ei v&#228;ltt&#228;m&#228;tt&#228; n&#228;e koko totuutta. Totuus on n&#228;iden kahden edell&#228; esitetyn k&#228;sitteellisten &#228;&#228;rip&#228;iden v&#228;liss&#228;.
”N&#228;k&#246;kulmia politiikkaan”-luento tarkasteli politiikkaa internet-ajan kontekstissa. Internet mahdollistaa uudenlaista vaalikeskustelua, mutta seurauksena ovat my&#246;s kuplat. Baymin kirjan mukaan poliittinen toiminta verkossa lis&#228;&#228; polarisaatiota sen sijaan, ett&#228; se synnytt&#228;isi keskustelua eri n&#228;k&#246;kulmien v&#228;lill&#228;. Verkkoyhteis&#246;t ovat homogeenisi&#228; ja ne rajoittavat p&#228;&#228;sy&#228; monipuolisiin n&#228;k&#246;kulmiin. (Baym 2015.) Kuplat eiv&#228;t kuitenkaan ole pelk&#228;st&#228;&#228;n ongelma, vaan niihin liittyy my&#246;s hy&#246;tyj&#228;. Kauppalehden (30.11.2017) jutussa “Siilojen, kuplien ja kuppikuntien puolesta” esitet&#228;&#228;n, ett&#228; ajatusten kehittyminen tarvitsee eristyneisyytt&#228;. van Dijk (2012) esitt&#228;&#228; kirjassaan pienten maailmojen lain (The law of small worlds), jonka mukaan verkossa on helppo saavuttaa muita; maailma on pieni ja kaikki ovat l&#228;hell&#228;. Voisiko ihmiskontaktien yll&#228;kyll&#228;isyyteen liitty&#228; sama dynamiikka kuin informaation ylt&#228;kyll&#228;isyyteen? Mahdollisesti olemme entist&#228; valikoivampia ihmiskontaktien suhteen, kun niit&#228; on tarjolla eritt&#228;in suuri m&#228;&#228;r&#228;. Keskustelun polarisoituminen on n&#228;kynyt viime aikoina sosiaalisessa mediassa, kuten esimerkiksi luennolla mainitulla Lis&#228;&#228; kaupunkia Helsinkiin -palstalla. Vaikka internetill&#228; on politiikan edist&#228;misen ty&#246;kaluna omat ongelmansa, sen k&#228;ytt&#246;&#228; pyrit&#228;&#228;n lis&#228;&#228;m&#228;&#228;n ihmisen osallistumisen ty&#246;kaluna. Ristiriitoja aiheuttavat lis&#228;ksi erilaiset n&#228;k&#246;kulmat; hallinto, n&#246;rtti ja kansalainen voivat olla eri mielt&#228; siit&#228;, miten virtuaaliset poliittiset areenat pit&#228;isi toteuttaa. Kun sivujen suunnittelu tehd&#228;&#228;n hallinnon n&#228;k&#246;kulmasta, hallinnon arvot ohjaavat ja rajaavat sit&#228;, miten kansalaiset voivat osallistua.
“Re-constructing digital democracy: An outline of four ‘positions’”-artikkelissa esitettiin nelj&#228; demokratian positiota (ks. Dahlberg 2011). Esimerkiksi “liberal-individualistic digital democracy” on riippuvainen siit&#228;, miten internet-sivut (esim. Kansalaisaloite.fi) on rakennettu. “Deliberative digital democracy” puolestaan riippuu siit&#228;, millaisia julkisuuden alustoja kansalaisille on tarjolla, ja “Counter-publics digital democracy” vastaavasti riippuu siit&#228; mink&#228;laisten verkkosivujen sallitaan toimia. Handbook of Internet Studies -kirjan luvun 21 artikkelissa ”Analyzing freedom of expression online: Theoretical, empirical and normative contributions” tuodaan esille, ett&#228; valtio voi sensuroida tai sulkea haluamiaan nettisivuja ja palvelimia (Dutton 2014). Demokratian positiot eiv&#228;t n&#228;iss&#228; olosuhteissa voi toimia t&#228;ysin vapaasti. Bitcoin-kryptovaluutta on hyv&#228; esimerkki “Autonomist Marxist digital democracy”:st&#228;. Kryptovaluutat mahdollistavat itseorganisoidun osallistumisen, joka on irrallaan keskitetyist&#228; j&#228;rjestelmist&#228; (mm. suuryrityksist&#228;, pankeista, valtioista). 
Handbook of Internet Studies -kirjan “Digital Inequality”-luvussa tarkastellaan digitaalisen teknologian ep&#228;tasa-arvoisuutta. Yht&#228;&#228;lt&#228; eriarvoisuutta on v&#228;est&#246;n eri segmenttien v&#228;lill&#228; sek&#228; globaalisti maiden v&#228;lill&#228;. Lis&#228;ksi eriarvoistumista voivat lis&#228;t&#228; eritasoiset ICT-taidot sek&#228; erot sosioekonomisessa asemassa. Toisaalta internet voi parantaa ihmisten mahdollisuuksia saada taitoja ja tietoa, joilla he voivat parantaa osaamistaan ja asemaansa ty&#246;markkinoilla. (Dutton 2014.) Ep&#228;tasa-arvoisessa verkkoyhteiskunnassa voi synty&#228; informaatioeliitti, jonka ymp&#228;rill&#228; on osallistuva enemmist&#246;. Osa ihmisist&#228; on suljettu ulkopuolelle. (van Dijk 2012, s. 206.) Internet on mielest&#228;ni kyseenalainen poliittisen vaikuttamisen edist&#228;minen kanava, koska se sulkee osan ihmisist&#228; ulkopuolisiksi. Kaikki suomalaiset eiv&#228;t k&#228;yt&#228; interneti&#228;, ja ne jotka eiv&#228;t k&#228;yt&#228; tai ne joilla ei ole siihen riitt&#228;vi&#228; taitoja, ovat eriarvoisessa asemassa suhteessa muihin.

L&#228;hteet
Baym, Nancy (2015) Personal Relations in the Digital Age.
BBC 24.07.2017: The people trying to fight fake news in India. Viitattu  13.12.2017. Saatavissa: http://www.bbc.com/news/world-asia-india-40657074
Dahlberg, L. (2011). Re-constructing digital democracy: An outline of four “positions.” New Media &amp; Society, 13(6), 855–872.
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Dutton, William (2014) Handbook of Internet Studies.
Kauppalehti 30.11.2017: Siilojen, kuplien ja kuppikuntien puolesta. Viitattu  13.12.2017. Saatavissa: https://www.kauppalehti.fi/uutiset/siilojen--kuplien-ja-kuppikuntien-puolesta/XmgGKB4Y
Winner, L. (1980). Do artifacts have politics? Daedalus, 121-136. 


20.11. SOSIAALINEN VUOROVAIKUTUS JA YHTEISTOIMINTA VERKKOALUSTOILLA

Handbook of Internet Studies -kirjan ”Network Societies and Internet Studies: Rethinking time, space, and class” artikkelissa esitet&#228;&#228;n, ett&#228; ajatukset yhten&#228;isest&#228; globaalista tietoyhteiskunnasta eiv&#228;t toimi k&#228;yt&#228;nn&#246;ss&#228;, vaan sen sijaan verkkoon on syntym&#228;ss&#228; useampia verkottuneita yhteiskuntia, joiden kulttuurinen kirjo on laaja (Dutton 2014). The Network Society kirjan mukaan puhumme verkkoyhteiskunnasta, mutta silti yhteiskunnassa on entist&#228; enemm&#228;n fragmentoitumista, individualisaatiota, vapautta ja itsen&#228;isyytt&#228;. Verkosto ja yksil&#246; ovat kolikon kaksi eri puolta; maailma ei koskaan ole ollut vapaampi, mutta se ei my&#246;sk&#228;&#228;n ole koskaan ollut n&#228;in yhteenkietoutunut. Yh&#228; useampi organisaatio on riippuvainen internetist&#228;. (van Dijk 2012.) Oheiskirjallisuudessa mainitaan lis&#228;ksi siirtym&#228; verkkoyhteis&#246;ist&#228; individualistisiin verkostoihin, joissa jokainen yksil&#246; on oman verkostonsa keskipiste (Baym 2015).
“Sosiaalisten rajojen hallinta yhteis&#246;palveluissa”-luennolla tarkasteltiin alustapalveluja ja jakamistaloutta. Jakamistalouden osalta keskustelu on usein ollut negatiivista; haluamme omistaa sen mit&#228; meill&#228; on, vaikka auto seisoo k&#228;ytt&#228;m&#228;tt&#228; suurimman osan ajasta. Airbnb-tutkimus osoitti, ett&#228; jakamistalous voi olla rahanvaihdon lis&#228;ksi my&#246;s sosiaalista vaihtoa josta on hy&#246;ty&#228; sosiaaliselle el&#228;m&#228;lle (Lampinen &amp; Cheshire 2016). Kun painopiste siirtyy sosiaaliseen vaihtoon, siit&#228; voi seurata ihmisten syrjint&#228;&#228;, koska ihmisill&#228; on taipumus suosia itsens&#228; kaltaisia ihmisi&#228;. Toiminnan sujuvoittamiseksi jakamistaloudessa tarvitaan selkeit&#228; s&#228;&#228;nt&#246;j&#228;, joiden m&#228;&#228;ritt&#228;misen ja seurannan osalta alustatoimijat ovat t&#228;rke&#228;ss&#228; asemassa. Alustatoimijan l&#228;sn&#228;olo ratkaisee my&#246;s luennolla mainitun kiitollisuuden velkaan j&#228;&#228;misen ongelman. Lis&#228;ksi luennolla todettiin, ett&#228; alustaa tarvitaan saatavilla olevien palvelujen kohdentamiseen. Vaikka luennolla korostettiin alustan olemassaolon t&#228;rkeytt&#228;, toiminta on mahdollista j&#228;rjest&#228;&#228; lohkoketjun kautta ilman v&#228;litt&#228;j&#228;organisaatiota tai muuta kolmatta osapuolta. Esittelen t&#228;m&#228;n reflektion loppupuolella Lockchain-teknologian, joka mahdollistaa t&#228;m&#228;n.
”Joukkoistettu verkko-oppiminen”-luento esitteli hoitoalan verkkokoulutusta ja ajatuksia siit&#228;, miten oleellista tietoa voitaisiin jakaa. Luennolla korostuivat verkkokoulutuksen hy&#246;dyt, kuten esimerkiksi laajan kohderyhm&#228;n saavuttaminen, yhteis&#246;n hy&#246;dynt&#228;minen, riippumattomuus paikasta ja taloudelliset syyt. Kriittisen n&#228;k&#246;kulman vahvistamiseksi perehdyin verkkokoulutuksen haasteisiin The Network Society -kirjan kautta. Kirjan mukaan verkko-opetuksen oppilaiden on vaikeampi vuorovaikuttaa kesken&#228;&#228;n, mik&#228; voi olla haaste yhteis&#246;n hy&#246;dynt&#228;miselle. Ongelmana voi my&#246;s olla ohjauksen ja auttamisen rajallisuus; monilla oppilailla ei ole riitt&#228;v&#228;&#228; itsekuria. Lis&#228;ksi kirjassa puhutaan sosiaalisesta erist&#228;ytymisest&#228;; perinteinen oppilaitos on tapaamisen ja sosialisoinnin paikka ja arkirutiinien luoja. Opiskelun erottaminen perhe-el&#228;m&#228;st&#228; voi my&#246;s olla ongelma joissain tapauksissa. (van Dijk 2012.) Omien kokemusteni mukaan verkko-opiskelu on suhteellisen hyv&#228; opiskelun muoto, mutta verkkoalustan keskustelut muiden opiskelijoiden kanssa j&#228;&#228;v&#228;t melko lyhyeksi; usein verkkokurssin alustalla keskustellaan minimivaatimusten edellytt&#228;m&#228;ss&#228; laajuudessa. Kasvokkaiset keskustelut venyv&#228;t pidemmiksi ja niiss&#228; aihetta k&#228;sitell&#228;&#228;n kokemusteni mukaan syv&#228;llisemmin.
Luennon j&#228;lkeisess&#228; keskusteluosuudesssa todettiin, ett&#228; Facebook, Uber ja Airbnb voivat kadota tulevaisuudessa, mutta syyt&#228; t&#228;h&#228;n ei spekuloitu sen tarkemmin. Airbnb on tarpeellinen, koska se tarjoaa alustan, jonka kautta voidaan v&#228;hent&#228;&#228; ep&#228;varmuutta tuntemattomien ihmisten v&#228;lill&#228; (Lampinen &amp; Cheshire 2016). Airbnb on mahdollista toteuttaa ilman yrityst&#228; lohkoketjuteknologiaa hy&#246;dynt&#228;en. Lockchain on lohkoketju ja kryptovaluutta, jonka on tarkoitus vastata samaan tarpeeseen kuin keskitetty Airbnb; siin&#228; Airbnb:n toiminnot on tarkoitus automatisoida siten, ett&#228; v&#228;litt&#228;j&#228;tahoa ei en&#228;&#228; tarvita. Airbnb:ss&#228; data on siiloutunut vain yrityksen k&#228;ytt&#246;&#246;n, mutta Lockchainissa data on kaikkien k&#228;yt&#246;ss&#228; ja kaikkien yll&#228;pit&#228;m&#228;&#228;. Dataa lis&#228;t&#228;&#228;n, poistetaan tai muutetaan Lockchain-tokenilla, joka on maksu tietokannan k&#228;yt&#246;st&#228;. Kun asiakas ja majoituksen tarjoaja ovat suoraan yhteydess&#228; toisiinsa tietokannan kautta, j&#228;&#228; perinteinen v&#228;lik&#228;si pois v&#228;list&#228; ja kustannukset pienenev&#228;t. Lockchainin esittelyvideo on katsottavissa osoitteessa: https://www.youtube.com/watch?time_continue=135&amp;v=tBWpTOhF2Kw

L&#228;hteet
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Dutton, William (2014) Handbook of Internet Studies.
Lampinen, A., &amp; Cheshire, C. (2016). Hosting via Airbnb: Motivations and financial assurances in monetized network hospitality. In Proceedings of the 2016 CHI Conference on Human Factors in Computing Systems (pp. 1669-1680).

27.11. ALUSTATOIMIJAT JA DATATALOUS

“Datatalous &amp; alustat”-luento esitti vertauskuvallisen kuvan &#246;ljynporauslautoista; data on uusi &#246;ljy ja suurimmat yritykset ovat nyky&#228;&#228;n datayrityksi&#228;. Kuten introluennolla todettiin, kuluttajien datasta on tullut arvonluonnin l&#228;hde. West (2017) esittelee artikkelissaan datakapitalismia. Toimintamme internetiss&#228; j&#228;tt&#228;&#228; digitaalisia j&#228;lki&#228;, jotka ker&#228;t&#228;&#228;n ja joita k&#228;ytet&#228;&#228;n k&#228;ytt&#228;ytymisemme ennustamiseen, mainostamiseen ja teknologian kehitt&#228;miseen. Datankeruu on pitk&#228;lti huomaamatonta, algoritmeja on vaikea ymm&#228;rt&#228;&#228; (West 2017). Datayritykset kilpailevat alustoista; yritykset kuten esimerkiksi Microsoft, Google ja Apple tarjoavat oman infrastruktuurinsa, k&#228;ytt&#246;j&#228;rjestelm&#228;ns&#228; ja ohjelmistonsa. van Dijk (2012) kutsuu t&#228;t&#228; toimintamallia kirjassaan totalitaariseksi ambitioksi, jossa k&#228;ytt&#228;j&#228; pyrit&#228;&#228;n sitomaan yrityksen ekosysteemiin. Yrityksen arvot vaikuttavat siihen, millainen niiden alusta on; nykyajan keskeisen&#228; ohjaavana arvona on datakapitalismi. Datakapitalismia vastaan on perustettu kampanjoita ja teknologioita, kuten esimerkiksi luennolla mainitut King Gafa, DuckDuckgo, Tor-verkko, Bitcoin ja #buytwitter.
”Case Aller Media”-luennolla todettiin sama asia joka on tullut puheeksi jo moneen kertaan t&#228;ll&#228; kurssilla: kaikki alkaa olla muutaman j&#228;tin k&#228;siss&#228;. Verkon kontrolli on pitk&#228;lti keskittynyt kahden yrityksen, Facebookin ja Googlen haltuun. Erityisesti Google on laajentanut toimintaansa uusille alueille kuten s&#228;hk&#246;postipalveluihin (ja niiden skannaamiseen mainostustarkoituksia varten) ja internetin k&#228;yt&#246;n laajamittaiseen seurantaan muun muassa cookies-seurannan avulla (West 2017). Luennolla mainittiin suuri muutos, joka on tulossa liittyen datan hallinnan oikeuksiin. S&#228;&#228;ntely on t&#228;h&#228;n menness&#228; onnistunut Euroopassa jossain m&#228;&#228;rin, mutta perustunut l&#228;hinn&#228; l&#228;pin&#228;kyvyyden lis&#228;&#228;miseen. Mielest&#228;ni l&#228;pin&#228;kyvyys ei yksin&#228;&#228;n auta asiaa, koska k&#228;ytt&#228;j&#228;n ainoa vaihtoehto on j&#228;tt&#228;yty&#228; kokonaan palvelujen ulkopuolelle, mik&#228; vaikeuttaisi el&#228;m&#228;&#228;. Mit&#228; enemm&#228;n verkostoon liittyy ihmisi&#228;, sit&#228; enemm&#228;n paineita muilla on liitty&#228; mukaan (The law of network externality, ks. van Dijk 2012). Dataj&#228;ttien toiminta datankeruun osalta ei kuitenkaan ole ainoastaan huono asia, koska datankeruuseen liittyy my&#246;s monenlaisia synergiaetuja. Esimerkiksi meille mainostetaan niit&#228; tuotteita, joita todenn&#228;k&#246;isesti haluamme. Saamme kohdennettua ja meille r&#228;&#228;t&#228;l&#246;ity&#228; palvelua. Teknologiaa voidaan my&#246;s datan pohjalta kehitt&#228;&#228; eteenp&#228;in.
Kauppalehden (24.2.2017) kolumnissa esitettiin ajatuksia terveydenhuollon asiakkaiden profiloinnista sosiaalisen median datan perusteella; kolumnin mukaan esimerkiksi luottohakemus voitaisiin tulevaisuudessa hyl&#228;t&#228; Facebook-p&#228;ivityksist&#228; tehtyjen terveysk&#228;ytt&#228;ytymisoletusten perusteella. Mielest&#228;ni t&#228;llainen teknologia ei kuitenkaan ole oikeudenmukainen, koska siit&#228; k&#228;rsiv&#228;t vain ne jotka ovat sosiaalisen median k&#228;ytt&#228;ji&#228;. Tietoja ei voida n&#228;in ollen ker&#228;t&#228; kaikista ihmisist&#228;. Eri ihmisten v&#228;lill&#228; on lis&#228;ksi eroja sen suhteen, kuinka usein ja mit&#228; he julkaisevat sosiaalisessa mediassa. Yksityisviestiketjujen data voisi silti olla suhteellisen luotettava tietol&#228;hde yksil&#246;&#228; arvioitaessa useimpien ihmisten tapauksessa.
Testatakseni mit&#228; johtop&#228;&#228;t&#246;ksi&#228; tekstidatasta voi tehd&#228;, kokeilin IBM:n kielellist&#228; teko&#228;lyohjelmaa Watsonia (Rajoitetusti k&#228;ytett&#228;viss&#228; osoitteessa: https://personality-insights-demo.ng.bluemix.net/). Watsonilla voidaan analysoida tekstin tai twiittien perusteella kirjoittajan persoonallisuuspiirteit&#228;. Kokeilu osoitti, ett&#228; Watson toimii  hyv&#228;n&#228; esimerkkin&#228; siit&#228; miten dataa voidaan analysoida ja tehd&#228; siit&#228; johtop&#228;&#228;t&#246;ksi&#228;. T&#228;llaisilla analyyseilla voisi olla laajamittaisessa k&#228;yt&#246;ss&#228; monia seurauksia: ty&#246;nantaja voisi esimerkiksi selvitt&#228;&#228; potentiaalisen ty&#246;ntekij&#228;n persoonallisuuspiirteet Twitter-tilin tai ty&#246;hakemuksen hakemuskirjeen tekstin perusteella. Watson ei ole viel&#228; k&#228;ytett&#228;viss&#228; suomen kielell&#228;, mutta voidaan odottaa, ett&#228; tulevaisuudessa n&#228;m&#228; teknologiat kehittyv&#228;t kiihtyv&#228;ll&#228; tahdilla ja ovat k&#228;ytett&#228;viss&#228; useammalle eri kielelle.  

L&#228;hteet
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Kauppalehti 24.2.2017: Kest&#228;&#228;k&#246; segmentti muutoksen? Viitattu  14.12.2017. Saatavissa: https://www.kauppalehti.fi/uutiset/kestaako-segmentti-muutoksen/2gSZGbKr 
West, S. M. (2017). Data capitalism: Redefining the logics of surveillance and privacy. Business &amp; Society, 0007650317718185.


4.12. ALGORITMIT, JULKISUUS JA MEDIA

“Algoritmit, julkisuus ja media”-luento tarkasteli hybridi&#228; mediatilaa ja sen luomaa julkisuutta. Luennon mukaan massamedia, sosiaalinen media ja hakukoneet rakentuvat yhteiseksi julkisuudeksi. Yht&#228;&#228;lt&#228; perinteisen median uutisointi vaikuttaa sosiaalisen median keskusteluihin, ja toisaalta perinteinen media poimii uutisoinnin aiheita sosiaalisesta mediasta. Yhten&#228; esimerkkin&#228; voisin mainita Sami Kiesin tapauksen, jossa h&#228;n p&#228;&#228;si YLE:n uutiseen sen j&#228;lkeen kun h&#228;nest&#228; oli jaettu sosiaaliseen mediaan huhu jonka mukaan h&#228;n olisi hakannut silloista tytt&#246;yst&#228;v&#228;&#228;ns&#228; (ks. YLE 8.12.2017). Asiasta oli meuhkannut sosiaalisessa mediassa yli 70 000 ihmist&#228;. Tapaus on tyypillinen esimerkki nykyp&#228;iv&#228;n sosiaalisen median kohun saamasta n&#228;kyvyydest&#228; ja osoittaa sen, miss&#228; laajuudessa yksityiset tapahtumat voivat saada huomattavaa julkisuutta sosiaalisessa mediassa. Hybridi mediatila on iso tarinakoneisto, kuten luennolla todettiin.
Yhteiskuntamme on muuttunut massayhteiskunnasta verkkoyhteiskunnaksi: massamedia v&#228;litti ennen maailmankuvaa traditionaalisille yhteis&#246;ille, nyt muodostuu l&#228;pileikkaavia virtuaalisia yhteis&#246;j&#228;. Seurauksena on julkisuuden fragmentoituminen ja useiden yksityisyyden alueiden syntyminen. (van Dijk 2012.) Fragmentoitumista edist&#228;&#228; omalta osaltaan luennolla ja artikkeleissa esitelty sosiaalinen filtter&#246;inti, joka liittyy huomiotalouden logiikkaan. Koska internetiss&#228; on liikaa tietoa (The law of limits to attention, ks. van Dijk 2012), tarvitaan filtter&#246;inti&#228; ja sit&#228; hoitavia tahoja kuten hakukoneita, selaimia, botteja, ohjelmistoja sek&#228; algoritmeja (Willson 2014), jotka pyrkiv&#228;t kilpailemaan huomiostamme n&#228;ytt&#228;m&#228;ll&#228; meille haluamaamme sis&#228;lt&#246;&#228;. Seurauksena ovat niin sanotut kaikukammiot (filter bubbles); uutisvirrassamme tai Googlen hakutuloksissamme n&#228;ytet&#228;&#228;n sellaista sis&#228;lt&#246;&#228; millaista haluamme n&#228;hd&#228;. Luennon esimerkiss&#228; tuotiin esille, ett&#228; demokraattien ja republikaanien kannattajat saavat googlatessaan eri hakutuloksia. 
Luennolla mainittiin, ett&#228; algoritmit ovat yht&#228; fiksuja tai tyhmi&#228; kuin me; usein vinoumat selittyv&#228;t opetusaineistolla eli omalla k&#228;ytt&#228;ytymisell&#228;. Olen kuitenkin eri mielt&#228; asiasta, koska uskon ett&#228; ihmisen toimintaan p&#228;tee polkuriippuvuus; sen sijaan ett&#228; olisimme tietynlaisia, meist&#228; tulee tietynlaisia. Algoritmit vahvistavat sit&#228; reitti&#228;, jolle olemme sattumalta p&#228;&#228;tyneet. Jos mietit&#228;&#228;n esimerkiksi Twitter-botin kiroilua, uskon ett&#228; kiroilu on yht&#228;lailla opittu ominaisuus, jonka sek&#228; ihmiset ett&#228; botit voivat oppia polkuriippuvuuden kautta.
“Media, algoritmit ja ennakoiva l&#246;yt&#228;minen”-luennolla todettiin heti alkuun, ett&#228; kilpailu huomiostamme kasvaa ja el&#228;mme vaihtoehtoisissa algoritmisissa todellisuuksissa. Itse olen aiemmin suhtautunut luottavaisesti hakukoneiden tarjoamaan sis&#228;lt&#246;&#246;n, mutta t&#228;st&#228; eteenp&#228;in suhtaudun ep&#228;ilev&#228;sti. Ajatus lukitusn&#228;yt&#246;st&#228; seuraavana askeleena uutisvirran j&#228;lkeen oli mielenkiintoinen; tosin tuntuu, ett&#228; nykyhetken ongelma ei ole pelk&#228;st&#228;&#228;n uutisvirrassa vaan informaation ylt&#228;kyll&#228;isyydess&#228;. Yksi syy, miksi en itse lataa YLE:n uutisvahtia on se, ett&#228; puhelimessani on liikaa ilmoituksia. T&#228;m&#228; johtuu osittain sovellusten m&#228;&#228;r&#228;n kasvusta. Olen laittanut suurimman osan ilmoituksista &#228;&#228;nett&#246;m&#228;lle. Uutisia luen silloin kun silt&#228; tuntuu, mutta jatkuva ilmoitusten saaminen uutisista ei kiinnosta itse&#228;ni.
P&#228;ivitt&#228;inen el&#228;m&#228; delegoidaan yh&#228; suuremmissa m&#228;&#228;rin online-areenoille. Kun ihmiset delegoivat el&#228;m&#228;&#228;ns&#228; verkkoon, t&#228;m&#228; tarjoaa suuryrityksille kuten Googlelle entist&#228; enemm&#228;n mahdollisuuksia hallita ja manipuloida dataa ja k&#228;ytt&#228;ji&#228;. Emme my&#246;sk&#228;&#228;n voi aina tiet&#228;&#228;, millaisia odotettuja ja odottamattomia seurauksia delegoimisella on; esimerkiksi ensimm&#228;isen luennon reflektiossa esittelin kulttuurin muutosta verkkodeittailun osalta (ks. introluento). Willsonin (2017) artikkelissa esitet&#228;&#228;n, ett&#228; algoritmit vahvistavat stereotypioita ja voivat vaikuttaa yst&#228;vyyssuhteisiin, identiteetteihin ja maailmankuvaan. Monet algoritmeista ovat yksityisomisteisia, joten niit&#228; on vaikea kritisoida ja ymm&#228;rt&#228;&#228;. (Willson 2017.) Luennon kysymysosiossa nostettiin esille ajatus siit&#228;, ett&#228; algoritmit voivat muodostaa feedback-luuppeja ja synnytt&#228;&#228; itse&#228;&#228;n toteuttavia ennusteita; seurauksena on yksil&#246;n k&#228;yt&#246;ksen muuttuminen yksipuoliseksi. Johtuvatko nyky-yhteiskunnan ongelmat algoritmeista, koska n&#228;it&#228; ongelmia ei ollut internetin alkuaikoina?
API on sovellus jonka kautta voidaan hakea verkkoalustan tietoja ja antaa sille k&#228;skyj&#228;. Sen kautta voidaan esimerkiksi rakentaa botti, jolla voidaan antaa Twitter-tilille k&#228;skyj&#228;. Latasin API:n kautta Helsingin Yliopiston Twitter-tilin tiedot. Tiedoista voidaan huomata se mik&#228; on julkista. Taustalla vaikuttavat algoritmit ovat piilotettuina ja suojattuina ja niihin ei p&#228;&#228;se k&#228;ytt&#246;liittym&#228;n kautta. Ainut tapa p&#228;&#228;st&#228; algoritmeihin k&#228;siksi olisi hakkeroitua palvelimille, joten niiden t&#228;sm&#228;llist&#228; toimintaa on vaikea selvitt&#228;&#228; ulkopuolisena. Algoritmien selvitt&#228;minen ilman hakkerointia vaatisi suuren m&#228;&#228;r&#228;n kokeiluja ja niiden perusteella algoritmien toiminnan p&#228;&#228;ttelemisen. API-sovellus siis osoittaa sen, ett&#228; algoritmit on piilotettu k&#228;ytt&#228;j&#228;n tai ulkopuolisen asiantuntijan tavoittamattomiin. 

L&#228;hteet
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Willson, M. (2014). The politics of social filtering. Convergence: The International Journal of Research into New Media Technologies, 20(2), 218–232.
Willson, M. (2017). Algorithms (and the) everyday. Information, Communication &amp; Society, 20(1), 137–150. 
YLE 8.12.2017: Nuori mies alkoi kitke&#228; kiusaamista kouluista ja sosiaalisesta mediasta – sitten h&#228;net leimattiin naistenhakkaajaksi. Viitattu  14.12.2017. Saatavissa: https://yle.fi/uutiset/3-9968038   
*/
    
}